# Generated by Django 5.1.1 on 2024-09-04 14:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название ресторана"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес ресторана"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+7",
                        max_length=128,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер стола")),
                (
                    "capacity",
                    models.IntegerField(verbose_name="Количество человек на стол"),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Забронирован"),
                ),
                (
                    "reserved_at",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        null=True,
                        verbose_name="Время резервирования",
                    ),
                ),
                (
                    "date_reserved",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата бронирования"
                    ),
                ),
                (
                    "time_reserved",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время бронирования"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurant.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
