# Generated by Django 5.1.1 on 2024-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер стола")),
                (
                    "capacity",
                    models.IntegerField(verbose_name="Количество человек на стол"),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Забронирован"),
                ),
            ],
        ),
    ]
