# Generated by Django 5.1.1 on 2024-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
    ]
