# Generated by Django 5.1.1 on 2024-09-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_remove_table_date_reserved_remove_table_reserved_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="table",
            old_name="capacity",
            new_name="seats",
        ),
    ]
