# Generated by Django 5.1.1 on 2024-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_booking_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отмены бронирования"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Бронь отменена"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активно"),
        ),
    ]
