# Generated by Django 5.1.1 on 2024-10-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_booking_cancelled_at_booking_is_cancelled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="is_cancelled",
        ),
        migrations.AlterField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="restaurant.table",
                verbose_name="Стол",
            ),
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Продолжительность бронирования"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(verbose_name="Время отмены бронирования"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="restaurant.table",
                        verbose_name="Стол",
                    ),
                ),
            ],
            options={
                "verbose_name": "История бронирования",
                "verbose_name_plural": "История бронирований",
            },
        ),
    ]
