# Generated by Django 5.1.1 on 2024-10-09 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_remove_booking_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
    ]
